---
# Refer to Ansible Builder Documentation for details for each options:
# https://ansible.readthedocs.io/projects/builder/en/latest/definition/

version: 3

# build_arg_defaults:
#   ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--pre"
#   ANSIBLE_GALAXY_CLI_ROLE_OPTS: "–no-deps"

images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal

options:
  # container_init:
  #   package_pip: dumb-init==1.2.5
  #   entrypoint: '["/opt/builder/bin/entrypoint", "dumb-init"]'
  #   cmd: '["bash"]'
  package_manager_path: /usr/bin/microdnf
  # relax_password_permissions: true
  # skip_ansible_check: false
  # workdir: /runner
  # user: 1000

dependencies:
#  python_interpreter:
#    package_system: python3.8
#    python_path: /usr/bin/python3.8
  ansible_core:
    package_pip: ansible-core~=2.15
  ansible_runner:
    package_pip: ansible-runner~=2.3
  system: bindep.txt
  python: requirements.txt
  galaxy: requirements.yml
